name       : kontactinterface
version    : 19.12.3
release    : 32
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.3/src/kontactinterface-19.12.3.tar.xz : 1a0392cbeb6833f4834c86f202ff06e5b6069d12100bffe37de6427f0531af89
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - extra-cmake-modules
    - kparts-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
