name       : kontactinterface
version    : 18.12.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.0/src/kontactinterface-18.12.0.tar.xz : 9f59ad01a633346780ba295aacad1a5462cf4192335df395206e04d8b3047d16
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kparts-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
