name       : kontactinterface
version    : 23.04.1
release    : 65
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.1/src/kontactinterface-23.04.1.tar.xz : 82f8322de306539ec2eed958b6cc3ebc9a102def9201d52a7b22e8e0a8977dd0
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - kparts-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
