name       : kontactinterface
version    : 20.04.0
release    : 34
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.0/src/kontactinterface-20.04.0.tar.xz : 0eb16f1d032bf6abf427118cbb1ac03701d55a7b544f490861c9adde94065e62
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - extra-cmake-modules
    - kparts-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
