name       : kontactinterface
version    : 21.08.0
release    : 51
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/kontactinterface-21.08.0.tar.xz : bff8684951ab22a7102b632a42f3d0456c3185022e166e03e34e414f844989be
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(x11)
    - kparts-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
