name       : kontactinterface
version    : 20.04.3
release    : 37
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.3/src/kontactinterface-20.04.3.tar.xz : 9c0587df91b9de55218d7313c445c68d13b22aeb09dc142caf8d8036574e3b09
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kparts-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
