name       : kontactinterface
version    : 19.08.3
release    : 27
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.3/src/kontactinterface-19.08.3.tar.xz : 67827b27e46d381a207bcd6986b0285c0b7629ec9b93048e9503768662e211dc
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - extra-cmake-modules
    - kiconthemes-devel
    - kparts-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
