name       : kontactinterface
version    : 21.08.3
release    : 54
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/kontactinterface-21.08.3.tar.xz : 52fd92c560ae1eaed5e9ce4058ade1bccae436ce38f04a682474b86699710489
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(x11)
    - kparts-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
