name       : kontactinterface
version    : 20.08.1
release    : 39
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.1/src/kontactinterface-20.08.1.tar.xz : 8272d0c17423a15e56e9e6d3979ee3017fd02ed996b8b6902c47312276ffeb51
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kparts-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
