name       : kontactinterface
version    : 23.04.0
release    : 64
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.0/src/kontactinterface-23.04.0.tar.xz : d7475f9abdb4809eaaf5aa78c4ac96f5118d84ceaa0015f70d3ed73f6c029cbb
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - kparts-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
