name       : kontactinterface
version    : 19.04.3
release    : 23
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.3/src/kontactinterface-19.04.3.tar.xz : d541daab32bddd6727b795d280be668be9da801ef7267159ea030f998b52ca74
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kparts-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
