name       : kontactinterface
version    : 20.12.3
release    : 46
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/kontactinterface-20.12.3.tar.xz : 3c9f395c2eaf843689e3ace68d8c06cbdbe914f4888657c676cdfe05ba981ddb
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(x11)
    - kparts-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
