name       : kontactinterface
version    : 21.04.0
release    : 47
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.0/src/kontactinterface-21.04.0.tar.xz : d51c282f477b8d32bf736169e8d56cbbc5fa3536247de9dd10d49646be3c9bc0
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(x11)
    - kparts-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
