name       : kontactinterface
version    : 17.04.1
release    : 1
source     :
    - https://download.kde.org/stable/applications/17.04.1/src/kontactinterface-17.04.1.tar.xz : 5719914f3ec67fc1eae5d92a884d1b463e773f15020f0557bda23e0d5d6d63f9
license    : LGPL-2.1
component  : desktop.library
summary    : Kontact Plugin Interface Library.
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5DBus)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kparts-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
    - kwallet-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
