name       : kontactinterface
version    : 18.08.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.0/src/kontactinterface-18.08.0.tar.xz : 161da1b646d21c42c3eb85605bcc5743caf3f94fdbe13d90c4fae2cf76bd9b55
license    : LGPL-2.1
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kparts-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
