name       : kontactinterface
version    : 21.04.1
release    : 48
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/kontactinterface-21.04.1.tar.xz : c9c9aee47286f26675a6cc67c987acc6970bc070ce843bddd5cc6e12a3c75899
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(x11)
    - kparts-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
