name       : kontactinterface
version    : 19.04.0
release    : 20
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.0/src/kontactinterface-19.04.0.tar.xz : 268005d61e97dab34f200b0e7a461afddb32a88ccc7c553b6c967865a6915392
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kparts-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
