name       : kontactinterface
version    : 19.12.1
release    : 30
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.1/src/kontactinterface-19.12.1.tar.xz : a88b782b495d662920fd5f51c287c472c107c577af92431b4470787a78866b2c
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - extra-cmake-modules
    - kparts-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
