name       : kontactinterface
version    : 22.04.2
release    : 60
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/kontactinterface-22.04.2.tar.xz : a6618c9f1340a65eba5c8f57395feae75fbf09152f55396f9b694dec1a4bfc5d
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(x11)
    - kparts-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
