name       : kontactinterface
version    : 22.04.0
release    : 58
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.0/src/kontactinterface-22.04.0.tar.xz : 17cea1cd9ecd88e4874fecc816a04e826a68cdf079b04feb6b28e116d0f21eec
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(x11)
    - kparts-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
