name       : kontactinterface
version    : 22.08.3
release    : 62
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/kontactinterface-22.08.3.tar.xz : bd44ff54c79fcd2a888ee31e1c7a711a7c80d6607e8812a88ed3d3eba6add411
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(x11)
    - kparts-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
