name       : kontactinterface
version    : 20.12.2
release    : 45
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/kontactinterface-20.12.2.tar.xz : 5a3982efe09e28d2b4af7e024df648eb19102052e0198029de95b04c6aec7344
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(x11)
    - kparts-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
