name       : kontactinterface
version    : 20.08.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.0/src/kontactinterface-20.08.0.tar.xz : 6b20e160642063b966f359ecf2e1946db161728d42f4e6b15a77f6a19f151048
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kparts-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
