name       : kontactinterface
version    : 21.04.2
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.2/src/kontactinterface-21.04.2.tar.xz : 6485b673f730d78e45290566ed91aa137e214addc3a3a7e4bab4cb2042102b01
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(x11)
    - kparts-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
