name       : kontactinterface
version    : 19.08.1
release    : 25
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.1/src/kontactinterface-19.08.1.tar.xz : adb5c380fd73102b84c72ea27975689dc289b0f5c8dd10f86bf0a857e00170be
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - extra-cmake-modules
    - kiconthemes-devel
    - kparts-devel
    - kwindowsystem-devel
    - libboost-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
