name       : kontactinterface
version    : 19.08.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.0/src/kontactinterface-19.08.0.tar.xz : e490fb4dc0e762d4f12a837ecbddc2f14276672d8f46d10029987222b372f3bc
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kparts-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
