name       : kontactinterface
version    : 23.04.3
release    : 67
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.3/src/kontactinterface-23.04.3.tar.xz : daba6cfaf5cd5350262bf7f555c599634bd27fe92431e79808a9eff42111cf99
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - kparts-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
