name       : kontactinterface
version    : 17.08.2
release    : 3
source     :
    - https://download.kde.org/stable/applications/17.08.2/src/kontactinterface-17.08.2.tar.xz : bee4d832d244722247b1b17e89547617eb82ec33dc9fb116c65e227de8469abf
license    : LGPL-2.1
component  : desktop.library
summary    : Kontact Plugin Interface Library.
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5DBus)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kparts-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
    - kwallet-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
