name       : kontactinterface
version    : 19.08.2
release    : 26
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/kontactinterface-19.08.2.tar.xz : cbd34915ddf6fbcf02395f7c876050f2b732f3769627489f04979e419cfdc869
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - extra-cmake-modules
    - kiconthemes-devel
    - kparts-devel
    - kwindowsystem-devel    
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
