name       : kontactinterface
version    : 19.12.2
release    : 31
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.2/src/kontactinterface-19.12.2.tar.xz : 3161e31476b4a6e870fd4134d20b2fbbfef075ec58a02f27830c9c5ea7dffa78
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - extra-cmake-modules
    - kparts-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
