name       : kontactinterface
version    : 18.08.3
release    : 15
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.3/src/kontactinterface-18.08.3.tar.xz : 63f770efbe9870c6ff747c7f0739832c0fc437f17d2bd80d95f4739179299d07
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kparts-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
