name       : kontactinterface
version    : 18.12.2
release    : 18
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.2/src/kontactinterface-18.12.2.tar.xz : 0e8afef75b0adf31122b18bce64cb6aa11d23fb603d2c4e75c5943119db50f11
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kparts-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
