name       : kontactinterface
version    : 17.12.2
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.2/src/kontactinterface-17.12.2.tar.xz : a39d6129793be51a7997fc16b1ca49251f8014fa6bc0d4af86ea317280f68d10
license    : LGPL-2.1
component  : desktop.library
summary    : Kontact Plugin Interface Library.
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5DBus)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kparts-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
    - kwallet-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
