name       : kontactinterface
version    : 20.12.0
release    : 42
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.0/src/kontactinterface-20.12.0.tar.xz : cf947c8cde12af33c25bd1fcca9a7f25828b75b25c38ea5250a1b4a9d5d188bb
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kparts-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
