name       : kontactinterface
version    : 21.08.2
release    : 53
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/kontactinterface-21.08.2.tar.xz : 8f5f0b86745273341b9f25bb24eb7bd12fe12894dce0886b47bf940f26655b71
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(x11)
    - kparts-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
