name       : kontactinterface
version    : 19.12.0
release    : 29
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.0/src/kontactinterface-19.12.0.tar.xz : d7c43f12779d908066f025354088aad44d0462e8e8807a6b8d71870f10a46578
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - extra-cmake-modules
    - kparts-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
