name       : kontactinterface
version    : 23.04.2
release    : 66
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/kontactinterface-23.04.2.tar.xz : 39566fa1ca2d37b167751419f93c5e8364a2dc6f6198852b3d5a45e14e97aed4
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - kparts-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
