name       : kontactinterface
version    : 17.12.1
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/kontactinterface-17.12.1.tar.xz : b42ba7b42c4f39c3049e6df181b5dba7e4b380b62110959589cb5560164a488d
license    : LGPL-2.1
component  : desktop.library
summary    : Kontact Plugin Interface Library.
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5DBus)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kparts-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
    - kwallet-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
