name       : kontactinterface
version    : 20.04.2
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.2/src/kontactinterface-20.04.2.tar.xz : 96429c896b9b084d96e9703bd5961a8288e1745744ee27cd31440d81edff08cc
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kparts-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
