name       : kontactinterface
version    : 20.08.3
release    : 41
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.3/src/kontactinterface-20.08.3.tar.xz : 43a2c396809bd5f82bdf84b152fd72840ff00f6f38abe913a91a012d494002aa
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kparts-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
