name       : kontactinterface
version    : 17.12.3
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.3/src/kontactinterface-17.12.3.tar.xz : 7ac2e040accd8fa5d756a37d5313e303aa46f5d8b8276a34683f17cad57fd196
license    : LGPL-2.1
component  : desktop.library
summary    : Kontact Plugin Interface Library.
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5DBus)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kparts-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
    - kwallet-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
