name       : kontactinterface
version    : 21.12.3
release    : 57
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/kontactinterface-21.12.3.tar.xz : e8b0408b7e634e9802ae81caaba3e154a5474a5bfc0c1981386dccb508069de3
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(x11)
    - kparts-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
