name       : kontactinterface
version    : 18.08.1
release    : 13
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.1/src/kontactinterface-18.08.1.tar.xz : 6bee6b0dd27140f4da98fa4abff7f7187d5830bb41d5a82c7ccac659b2e726f1
license    : LGPL-2.1
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kparts-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
