name       : kontactinterface
version    : 20.12.1
release    : 43
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.1/src/kontactinterface-20.12.1.tar.xz : 923c18164e5973494cb30a0dc407714a3895895c241a43b44f5ae4b8797db469
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kparts-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
