name       : kontactinterface
version    : 18.12.1
release    : 17
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.1/src/kontactinterface-18.12.1.tar.xz : c12c8fa79ab821f429a427871514e16987e69c65cb145b6a2551f26bf9500b4e
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kparts-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
