name       : kontactinterface
version    : 21.12.0
release    : 55
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/kontactinterface-21.12.0.tar.xz : 7b4849eab07b26ef9406fe7afcfe011116502dbc1eaffa1ea8a819575d4c9f07
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(x11)
    - kparts-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
